# Generated by Django 3.0.6 on 2020-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='content',
        ),
    ]
